baseURL = 'https://lucasjournal.com.br/'
locale = 'pt-br'
title = 'Lucas Journal'
theme = 'PaperMod'

[params]
  subtitle = "Notas de um padawan de computação"
  mainSections = ["posts"]
  disableSpecial1stPost = true
