baseURL = 'https://lucasjournal.com.br/'
locale = 'pt-br'
title = 'Lucas-Journal'
theme = 'hextra'

[[menu.main]]
  name = "Tema"
  weight = 1
  [menu.main.params]
    type = "theme-toggle"

[params]
  description = "Notas de um padawan de computação"

  [params.navbar]
    displayTitle = true
    displayLogo = false

  [params.theme]
    default = "system"
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = true

  [params.blog.list]
    sortBy = "date"
    sortOrder = "desc"
    displayTags = true

  [params.blog.article]
    displayPagination = true
